### ISSUE TITLE
Collapsible function problem on peanutbase-stage Gene expression atlases pages

### ISSUE THREAD

**Issue by weihuang12** [legumeinfo/PeanutbaseWebsite#13]
When I was browsing through Gene expression atlases pages on peanutbase-stage, I noticed all the collapsible functions are gone. 
For example, 
Arachis Gene Atlas
Click for a description of the table, and credits and usage agreement

It has already expanded before clicking on it. 
But the collapsible function on production is fine. Did anything change on stage? I didn't see any code changes.

**Comment by adf-ncgr** [comment]
Hi Wei-
this sounds similar to other problems that were solved on other hosts by doing drush cc all; I don't think pb-stage had this done so I'll try it and let you know when you can look again

**Comment by adf-ncgr** [comment]
OK, I think it looks like it's working now but please confirm and close the issue if appropriate

**Comment by weihuang12** [comment]
Yes. It is working. I will close the issue. Thanks, Andrew.
