### ISSUE TITLE
Home page button for DataStore: 400 Bad request.

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/PeanutbaseWebsite#2]
Bad Request
Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.

**Comment by sdash-github** [comment]
Coded as href="/data/public". How to make it https instead of http??

**Comment by adf-ncgr** [comment]
production site seems fine for me in this regard using chrome browser. I think that href should 
simply inherit the protocol used to load the page it was on. Did you somehow get the home page to load without using https: ? I didn't think the site would allow that, but I'm unclear how you got that error.

**Comment by sdash-github** [comment]
Now making sense to me:
I used https://localhost:6802/home but it has 'Not Secure' sign right near the URL.
Because my tunnel is 'Not Secure' to start with when I started the tunell by accepting to start the page that way. So, my guess is, it should disappear in the production.

**Comment by sdash-github** [comment]
No more an issue. Close
