### ISSUE TITLE
Germplasm images in PB: Erratic behavior 

### ISSUE THREAD

**Issue by sdash-github** [legumeinfo/PeanutbaseWebsite#3]
Ex-1: https://peanutbase.org/germplasm/images/2012_NC_Isleib_regeneration_seeds
-- Shows up in FireFox but not in Chrome even after several reloads.  But didn't show up in either of the browsers when tested another time in another place (CGIL).
--Checked in lis-stage and it shows up in Chrome.  Then rechecked in PB production and it shows up.

Ex-2. https://peanutbase.org/germplasm/images/2012_NC_Isleib_regeneration_pods
Shows up in both FF and Chrome.

I have no idea what is causing this.  The server log doesn't show anything that relates to it..

**Comment by sdash-github** [comment]
In another computer (Mac OS X too) in the household:
Ex-1: doesn't appear in FF or Chrome
Ex-2: Appears in both

**Comment by nathanweeks** [comment]
In Chrome DevTools I saw a bunch of ERR_CONNECTION_REFUSED errors; in the network tab the URLs were of the form http://localhost:8082/... I logged in to Drupal, navigated to /admin/config/media/brilliant_gallery/manage , clicked on an image folder, was greeted with "Error: The website encountered an unexpected error. Please try again later", refreshed the page at https://peanutbase.org/germplasm/images/2012_NC_Isleib_regeneration_seeds, and then I could see the images...

Maybe some weird Drupal caching issue?

**Comment by adf-ncgr** [comment]
FWIW, I still get the localhost errors in the console when accessing:
https://peanutbase.org/germplasm/images/2012_NC_Isleib_regeneration_seeds
although the port listed for me is 6802 not 8082; this may or may not be significant in further diagnosing the issue but it seems a little weird (unless perhaps @nathanweeks just made an accounting error...)

**Comment by sdash-github** [comment]
Port 6802 is when I tunnel into pb-stage:
-L6802:peanutbase-stage:443.  But why should it appear in your browser console for production site?

**Comment by adf-ncgr** [comment]
Is it possible that you might have accidentally copy-pasted an absolute URL into a config somewhere? Failing that, I have no idea.

**Comment by sdash-github** [comment]
I haven't touched its config in years now.  But I'll look in the Drupal module admin pages. Nathan has already gone through that recently while addressing a more fundamental issue for Brilliant Gallery, #1

**Comment by adf-ncgr** [comment]
after failing to find any config for the brilliant gallery in the admin, I invoked the deep dark drupal magic incantation:
drush cc all (x3)
and this seems to have fixed it for me on production.

**Comment by adf-ncgr** [comment]
I haven't done this on stage, which still exhibits the behavior for me, but you probably don't notice it if you tunnel into stage using that. I guess the moral of the story is probably that Nathan was right about the weird caching and it may be wise to do this cache clearing after a rollover to prod.

**Comment by nathanweeks** [comment]
It probably was localhost:6082 for me as well (I was trying to recall the port after the problem was resolved). 

Re: peanutbase-stage: after a "drush cc all", /germplasm/images/2012_NC_Isleib_regeneration_seeds displays correctly.

**Comment by sdash-github** [comment]
Resolved.
